const userroutes = require("./user.routes");
const authroutes = require("./auth.routes");
const customerroutes = require("./customer.routes");
const leadroutes = require("./lead.routes");
const dealroutes = require("./deal.routes");
const dashboardroutes = require("./dashboard.routes");
const activityroutes = require("./activity.routes");
const Conversationroutes = require("./conversation.routes");
const followUpRoutes = require("./followUp.routes");
const noteRoutes = require("./note.routes");
const express = require("express");
const router = express.Router();
router.use("/auth", authroutes);
router.use("/users", userroutes);
router.use("/customers", customerroutes);
router.use("/leads", leadroutes);
router.use("/deals", dealroutes);
router.use("/dashboard", dashboardroutes);
router.use("/activities", activityroutes);
router.use("/conversations", Conversationroutes);
router.use("/followups", followUpRoutes);
router.use("/notes", noteRoutes);
module.exports = router;
